### ISSUE TITLE
Bring changes to the framework back to upstream - just develop tests on our side

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/smashbox#68]
Changes, that needs to be provided to upstream (all with the Framework label)
- [x] Ignore the pycoclient folder and the local config #52 -> cernbox/smashbox#16
- [x] specify that we want python2 #53 -> cernbox/smashbox#7
- [x]  add support for the loop argument to loop over a test run #56 -> cernbox/smashbox#13
- [x]  added scp_port to template for scp commands #57 -> cernbox/smashbox#14
- [x]  pass in verify_certs to Client constructor #59 -> cernbox/smashbox#15
- [x] deduplicate decode -> cernbox/smashbox#17
- [x] rundir not unique #62 -> cernbox/smashbox#19
- [x] login new users for encryption key generation #70 -> cernbox/smashbox#22
- [x] shareFile checks for failed share incorrectly #83 => cernbox/smashbox#26
- [x] Share group test does not reset accounts correctly #73 and #106 => cernbox/smashbox#25
- [x] Return code of tests on error #96 => cernbox/smashbox#24
- [x] Make scrape log optional and fix it => cernbox/smashbox#35

**Comment by MorrisJobke** [comment]
python2 -> cernbox/smashbox#7

**Comment by MorrisJobke** [comment]
loop parameter -> cernbox/smashbox#13

**Comment by MorrisJobke** [comment]
scp_port -> cernbox/smashbox#14

**Comment by MorrisJobke** [comment]
verify_certs -> cernbox/smashbox#15

**Comment by MorrisJobke** [comment]
gitignore -> cernbox/smashbox#16

**Comment by MorrisJobke** [comment]
deduplicate decode -> cernbox/smashbox#17

**Comment by nickvergessen** [comment]
Sent some more to upstream https://github.com/cernbox/smashbox/pull/24, https://github.com/cernbox/smashbox/pull/25, https://github.com/cernbox/smashbox/pull/26
Also they broke scrap log: https://github.com/cernbox/smashbox/pull/27

Currently open:
- ~~Require python2: https://github.com/cernbox/smashbox/pull/7~~
- ~~Do not check certs: https://github.com/cernbox/smashbox/pull/15~~
- Reset the log file before the test and check the log on each test

Apart from that the diff is empty in the direction from us to them, so we only miss changes they did.
I will prepare the reset + scrap patch aswell, then we should be ready for our reset.

**Comment by MorrisJobke** [comment]
:+1:

**Comment by nickvergessen** [comment]
Yay, so just the broken scrapping with local smashbox is left :)

**Comment by nickvergessen** [comment]
And scrapping the log in each test and reseting it before the test, to make sure we only check for the desired time

**Comment by nickvergessen** [comment]
One last PR: https://github.com/cernbox/smashbox/pull/35
