### ISSUE TITLE
Weekly stats report

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/smashbox#88]
Until this is done on Jenkins/CI, I will keep publishing my report here
# May 21:
### ownCloud Community tests
- [x] `bin/smash lib/oc-tests/test_reshareDir.py`
- [x] `bin/smash lib/oc-tests/test_scrapeLogFile.py`
- [x] `bin/smash lib/oc-tests/test_shareDir.py`
- [x] `bin/smash lib/oc-tests/test_shareFile.py -t=0`
- [x] `bin/smash lib/oc-tests/test_shareFile.py -t=1`
- [x] `bin/smash lib/oc-tests/test_shareFile.py -t=2`
- [x] `bin/smash lib/oc-tests/test_shareGroup.py`
- [x] `bin/smash lib/oc-tests/test_sharePermissions.py -t=0`
- [x] `bin/smash lib/oc-tests/test_sharePermissions.py -t=1`
- [x] `bin/smash lib/oc-tests/test_sharePermissions.py -t=2`
- [x] `bin/smash lib/oc-tests/test_sharePermissions.py -t=3`
- [x] `bin/smash lib/oc-tests/test_sharePermissions.py -t=4`
- [x] `bin/smash lib/oc-tests/test_sharePermissions.py -t=5`
- [x] `bin/smash lib/oc-tests/test_sharePermissions.py -t=6`
- [x] `bin/smash lib/oc-tests/test_sharePermissions.py -t=7`
- [x] `bin/smash lib/oc-tests/test_uploadFiles.py -t=0` => Issue: #89 -- PR: #90 
- [x] `bin/smash lib/oc-tests/test_uploadFiles.py -t=1` => Issue: #89 -- PR: #90 
- [x] `bin/smash lib/oc-tests/test_uploadFiles.py -t=2` => Issue: #89 -- PR: #90 
### Cern tests
- [x] `bin/smash lib/test_basicSync.py -t=0`
- [x] `bin/smash lib/test_basicSync.py -t=1`
- [x] `bin/smash lib/test_basicSync.py -t=2`
- [x] `bin/smash lib/test_basicSync.py -t=3`
- [x] `bin/smash lib/test_basicSync.py -t=4`
- [x] `bin/smash lib/test_basicSync.py -t=5`
- [x] `bin/smash lib/test_basicSync.py -t=6`
- [x] `bin/smash lib/test_basicSync.py -t=7`
- [x] `bin/smash lib/test_concurrentDirMove.py -t=0`
- [x] `bin/smash lib/test_concurrentDirMove.py -t=1`
- [x] `bin/smash lib/test_concurrentDirMove.py -t=2`
- [x] `bin/smash lib/test_concurrentDirMove.py -t=3`
- [x] `bin/smash lib/test_concurrentDirMove.py -t=4`
- [x] `bin/smash lib/test_concurrentDirRemove.py -t=0`
- [x] `bin/smash lib/test_concurrentDirRemove.py -t=1`
- [x] `bin/smash lib/test_concurrentDirRemove.py -t=2`
- [x] `bin/smash lib/test_dirMove.py -t=0`
- [x] `bin/smash lib/test_dirMove.py -t=1`
- [x] `bin/smash lib/test_dirMove.py -t=2`
- [x] `bin/smash lib/test_dirMove.py -t=3`
- [x] `bin/smash lib/test_fileMove.py -t=0`
- [x] `bin/smash lib/test_nplusone.py -t=0`
- [x] `bin/smash lib/test_nplusone.py -t=1`
- [x] `bin/smash lib/test_nplusone.py -t=2`
- [x] `bin/smash lib/test_nplusone.py -t=3`
- [x] `bin/smash lib/test_nplusone.py -t=4`
- [x] `bin/smash lib/test_pingpong.py`
- [x] `bin/smash lib/test_slowwrite.py -t=0`
- [x] `bin/smash lib/test_slowwrite.py -t=1`
- [x] `bin/smash lib/test_slowwrite.py -t=2`
- [x] `bin/smash lib/test_slowwrite.py -t=3`
- [x] `bin/smash lib/test_storm.py`
- [x] `bin/smash lib/test_userload.py`
#### Still failing
- [ ] `bin/smash lib/test_concurrentOverwriteFile.py`
- [ ] `bin/smash lib/test_nplustwo.py`
- [ ] `bin/smash lib/test_slowwrite.py -t=4`
#### Allowed to fail for now:
- [ ] `bin/smash lib/test_filenames.py`
- [ ] `bin/smash lib/test_unicodejam.py`

**Comment by nickvergessen** [comment]
# May 21:

## WITH Encryption

### ownCloud Community tests
- [x] `bin/smash lib/oc-tests/test_reshareDir.py`
- [x] `bin/smash lib/oc-tests/test_scrapeLogFile.py`
- [x] `bin/smash lib/oc-tests/test_shareDir.py`
- [x] `bin/smash lib/oc-tests/test_shareFile.py -t=0`
- [x] `bin/smash lib/oc-tests/test_shareFile.py -t=1`
- [x] `bin/smash lib/oc-tests/test_shareFile.py -t=2`
- [x] `bin/smash lib/oc-tests/test_shareGroup.py`
- [x] `bin/smash lib/oc-tests/test_sharePermissions.py -t=0`
- [x] `bin/smash lib/oc-tests/test_sharePermissions.py -t=1`
- [x] `bin/smash lib/oc-tests/test_sharePermissions.py -t=2`
- [x] `bin/smash lib/oc-tests/test_sharePermissions.py -t=3`
- [x] `bin/smash lib/oc-tests/test_sharePermissions.py -t=4`
- [x] `bin/smash lib/oc-tests/test_sharePermissions.py -t=5`
- [x] `bin/smash lib/oc-tests/test_sharePermissions.py -t=6`
- [x] `bin/smash lib/oc-tests/test_sharePermissions.py -t=7`
- [x] `bin/smash lib/oc-tests/test_uploadFiles.py -t=0` => Issue: #89 -- PR: #90 
- [x] `bin/smash lib/oc-tests/test_uploadFiles.py -t=1` => Issue: #89 -- PR: #90 
- [x] `bin/smash lib/oc-tests/test_uploadFiles.py -t=2` => Issue: #89 -- PR: #90 

### Cern tests
- [x] `bin/smash lib/test_basicSync.py -t=0`
- [x] `bin/smash lib/test_basicSync.py -t=1`
- [x] `bin/smash lib/test_basicSync.py -t=2`
- [x] `bin/smash lib/test_basicSync.py -t=3`
- [x] `bin/smash lib/test_basicSync.py -t=4`
- [x] `bin/smash lib/test_basicSync.py -t=5`
- [x] `bin/smash lib/test_basicSync.py -t=6`
- [x] `bin/smash lib/test_basicSync.py -t=7`
- [x] `bin/smash lib/test_concurrentDirMove.py -t=0`
- [x] `bin/smash lib/test_concurrentDirMove.py -t=1`
- [x] `bin/smash lib/test_concurrentDirMove.py -t=2`
- [x] `bin/smash lib/test_concurrentDirMove.py -t=3`
- [x] `bin/smash lib/test_concurrentDirMove.py -t=4`
- [x] `bin/smash lib/test_concurrentDirRemove.py -t=0`
- [x] `bin/smash lib/test_concurrentDirRemove.py -t=1`
- [x] `bin/smash lib/test_concurrentDirRemove.py -t=2`
- [x] `bin/smash lib/test_dirMove.py -t=0`
- [x] `bin/smash lib/test_dirMove.py -t=1`
- [x] `bin/smash lib/test_dirMove.py -t=2`
- [x] `bin/smash lib/test_dirMove.py -t=3`
- [x] `bin/smash lib/test_fileMove.py -t=0`
- [x] `bin/smash lib/test_nplusone.py -t=0`
- [x] `bin/smash lib/test_nplusone.py -t=1`
- [x] `bin/smash lib/test_nplusone.py -t=2`
- [x] `bin/smash lib/test_nplusone.py -t=3`
- [x] `bin/smash lib/test_nplusone.py -t=4`
- [x] `bin/smash lib/test_pingpong.py`
- [x] `bin/smash lib/test_slowwrite.py -t=0`
- [x] `bin/smash lib/test_slowwrite.py -t=1`
- [x] `bin/smash lib/test_slowwrite.py -t=2`
- [x] `bin/smash lib/test_slowwrite.py -t=3`
- [ ] `bin/smash lib/test_storm.py`
- [x] `bin/smash lib/test_userload.py`

#### Still failing
- [ ] `bin/smash lib/test_concurrentOverwriteFile.py`
- [ ] `bin/smash lib/test_nplustwo.py`
- [ ] `bin/smash lib/test_slowwrite.py -t=4`

#### Allowed to fail for now:
- [ ] `bin/smash lib/test_filenames.py`
- [ ] `bin/smash lib/test_unicodejam.py`

**Comment by DeepDiver1975** [comment]
Awesome idea! Many thanks!

**Comment by nickvergessen** [comment]
One test that worked before is failiing. I created a new issue https://github.com/owncloud/smashbox/issues/89 and will investigate it tomorrow whether it's an issue with the test (unlikly since it passed before) or with owncloud (recent change?!)

**Comment by nickvergessen** [comment]
#89 has been fixed with #90 so we are back to green.
