### ISSUE TITLE
Smashing 7.0.5 server

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/smashbox#92]
Following @nickvergessen idea we can track the execution of tests against 7.0.5 server.

Many test probably will fail  because of api changes or improvements in smashbox not allowed in 7. Anyway i think it is useful to have that info tracked here.
### ownCloud Community tests
- [ ] `bin/smash lib/oc-tests/test_reshareDir.py`
- [ ] `bin/smash lib/oc-tests/test_scrapeLogFile.py`
- [ ] `bin/smash lib/oc-tests/test_shareDir.py`
- [ ] `bin/smash lib/oc-tests/test_shareFile.py -t=0`
- [ ] `bin/smash lib/oc-tests/test_shareFile.py -t=1`
- [ ] `bin/smash lib/oc-tests/test_shareFile.py -t=2`
- [ ] `bin/smash lib/oc-tests/test_shareGroup.py`
- [ ] `bin/smash lib/oc-tests/test_sharePermissions.py -t=0`
- [ ] `bin/smash lib/oc-tests/test_sharePermissions.py -t=1`
- [ ] `bin/smash lib/oc-tests/test_sharePermissions.py -t=2`
- [ ] `bin/smash lib/oc-tests/test_sharePermissions.py -t=3`
- [ ] `bin/smash lib/oc-tests/test_sharePermissions.py -t=4`
- [ ] `bin/smash lib/oc-tests/test_sharePermissions.py -t=5`
- [ ] `bin/smash lib/oc-tests/test_sharePermissions.py -t=6`
- [ ] `bin/smash lib/oc-tests/test_sharePermissions.py -t=7`
- [ ] `bin/smash lib/oc-tests/test_uploadFiles.py -t=0` => Issue: #89 -- PR: #90 
- [ ] `bin/smash lib/oc-tests/test_uploadFiles.py -t=1` => Issue: #89 -- PR: #90 
- [ ] `bin/smash lib/oc-tests/test_uploadFiles.py -t=2` => Issue: #89 -- PR: #90 
### Cern tests
- [x] `bin/smash lib/test_basicSync.py -t=0`
- [x] `bin/smash lib/test_basicSync.py -t=1`
- [x] `bin/smash lib/test_basicSync.py -t=2`
- [ ] `bin/smash lib/test_basicSync.py -t=3`
- [ ] `bin/smash lib/test_basicSync.py -t=4`
- [ ] `bin/smash lib/test_basicSync.py -t=5`
- [ ] `bin/smash lib/test_basicSync.py -t=6`
- [ ] `bin/smash lib/test_basicSync.py -t=7`
- [ ] `bin/smash lib/test_concurrentDirMove.py -t=0`
- [ ] `bin/smash lib/test_concurrentDirMove.py -t=1`
- [ ] `bin/smash lib/test_concurrentDirMove.py -t=2`
- [ ] `bin/smash lib/test_concurrentDirMove.py -t=3`
- [ ] `bin/smash lib/test_concurrentDirMove.py -t=4`
- [ ] `bin/smash lib/test_concurrentDirRemove.py -t=0`
- [ ] `bin/smash lib/test_concurrentDirRemove.py -t=1`
- [ ] `bin/smash lib/test_concurrentDirRemove.py -t=2`
- [ ] `bin/smash lib/test_dirMove.py -t=0`
- [ ] `bin/smash lib/test_dirMove.py -t=1`
- [ ] `bin/smash lib/test_dirMove.py -t=2`
- [ ] `bin/smash lib/test_dirMove.py -t=3`
- [ ] `bin/smash lib/test_fileMove.py -t=0`
- [ ] `bin/smash lib/test_nplusone.py -t=0`
- [ ] `bin/smash lib/test_nplusone.py -t=1`
- [ ] `bin/smash lib/test_nplusone.py -t=2`
- [ ] `bin/smash lib/test_nplusone.py -t=3`
- [ ] `bin/smash lib/test_nplusone.py -t=4`
- [ ] `bin/smash lib/test_pingpong.py`
- [ ] `bin/smash lib/test_slowwrite.py -t=0`
- [ ] `bin/smash lib/test_slowwrite.py -t=1`
- [ ] `bin/smash lib/test_slowwrite.py -t=2`
- [ ] `bin/smash lib/test_slowwrite.py -t=3`
- [ ] `bin/smash lib/test_storm.py`
- [ ] `bin/smash lib/test_userload.py`
